# Tensor Flow

### 読み込み

In [1]:
import torch

In [2]:
### 配列

In [3]:
torch.tensor([0,1,2,3])

tensor([0, 1, 2, 3])

### 変数

In [4]:
torch.Tensor(2,3)

tensor([[3.5733e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

### 1~6までの配列を作成し、2個、中身の要素3個の配列を作成

In [5]:
torch.arange(6).reshape(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

### 行列積（内積、行列積）

In [6]:
a0 = torch.tensor([1.,2.,3.,4.])
a1 = torch.tensor([5.,6.,7.,8.])
torch.matmul(a0, a1)

tensor(70.)

## pyTorchの学習プログラムの設定方法

階層は合計５つ作成。  
(1) データの準備。設定  
(2)   
class MyModel (nn.Module):  
    def __init__(self):  
        super(MyModel, self).__init__()  
        利用するnnクラスの関数の宣言  
    def forward(self. ....):  
   　順方向の計算  
(3) model = MyModel()  
       optimizer = 最適化アルゴリズム  
       criterion = 誤差関数  
(4) for epoch in range(繰り返し回数):  
        データの加工(input, target の作成)  
        output = model(input)  
        loss = criterion(output, target)  
        optimizer.zero_grad()  
        loss.backward()  
        optimizer.step()  
(5) 結果の出力  

### 絶対使うライブラリ

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np

In [11]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
xtrain, xtest, ytrain, ytest = train_test_split(iris.data, iris.target, test_size=0.5)
# torchにした。
xtrain = torch.from_numpy(xtrain).type('torch.FloatTensor')
ytrain = torch.from_numpy(ytrain).type('torch.LongTensor')
xtest = torch.from_numpy(xtest).type('torch.FloatTensor')
ytest = torch.from_numpy(ytest).type('torch.LongTensor')

### ニューラルネットでモデル化

In [14]:
class MyIris(nn.Module):
    def __init__(self):
        super(MyIris, self).__init__()
        self.l1 = nn.Linear(4,6)
        self.l2 = nn.Linear(6, 3)
    def forward(self, x):
        h1 = torch.sigmoid(self.l1(x))
        h2 = self.l2(h1)
        return h2

In [15]:
model = MyIris() # モデル
optimizer = optim.SGD(model.parameters(), lr=0.1) # 確率的勾配降下法 パラメータと学習率を書く
criterion = nn.CrossEntropyLoss() # 回帰は平均二乗誤差、　識別はこのようにクロスエントロピーを用いる

### 学習 (最急降下法)

In [17]:
for i in range(1000):
    output = model(xtrain)
    loss=criterion(output, ytrain)
    print(i, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 1.1771607398986816
1 1.1596921682357788
2 1.1463850736618042
3 1.1361656188964844
4 1.128237247467041
5 1.1220122575759888
6 1.1170578002929688
7 1.1130541563034058
8 1.1097640991210938
9 1.1070109605789185
10 1.1046624183654785
11 1.1026184558868408
12 1.1008028984069824
13 1.099157691001892
14 1.0976383686065674
15 1.0962097644805908
16 1.094844937324524
17 1.0935227870941162
18 1.0922257900238037
19 1.0909404754638672
20 1.0896557569503784
21 1.0883625745773315
22 1.0870535373687744
23 1.0857223272323608
24 1.0843639373779297
25 1.082973599433899
26 1.0815476179122925
27 1.0800822973251343
28 1.078574538230896
29 1.0770210027694702
30 1.0754191875457764
31 1.073765516281128
32 1.0720572471618652
33 1.07029128074646
34 1.0684632062911987
35 1.0665698051452637
36 1.064606785774231
37 1.062569499015808
38 1.0604530572891235
39 1.0582529306411743
40 1.055963397026062
41 1.0535799264907837
42 1.0510972738265991
43 1.0485116243362427
44 1.0458195209503174
45 1.0430184602737427
46 1.0401

408 0.46237534284591675
409 0.4618411362171173
410 0.46130645275115967
411 0.46077123284339905
412 0.46023550629615784
413 0.4596991539001465
414 0.4591623544692993
415 0.45862486958503723
416 0.4580870568752289
417 0.4575485289096832
418 0.45700952410697937
419 0.45646998286247253
420 0.4559299647808075
421 0.4553893506526947
422 0.45484817028045654
423 0.45430660247802734
424 0.453764408826828
425 0.4532216489315033
426 0.452678382396698
427 0.4521346390247345
428 0.45159032940864563
429 0.45104554295539856
430 0.45050013065338135
431 0.4499543309211731
432 0.44940802454948425
433 0.44886112213134766
434 0.44831374287605286
435 0.44776585698127747
436 0.4472174644470215
437 0.4466686546802521
438 0.4461192190647125
439 0.44556936621665955
440 0.44501903653144836
441 0.444468230009079
442 0.44391682744026184
443 0.4433650076389313
444 0.4428127408027649
445 0.44226008653640747
446 0.4417068362236023
447 0.4411531686782837
448 0.4405989944934845
449 0.4400444030761719
450 0.43948933482

897 0.22047366201877594
898 0.22014732658863068
899 0.21982170641422272
900 0.219496950507164
901 0.21917285025119781
902 0.21884958446025848
903 0.21852698922157288
904 0.21820522844791412
905 0.21788416802883148
906 0.21756385266780853
907 0.21724431216716766
908 0.2169254869222641
909 0.21660740673542023
910 0.21629008650779724
911 0.21597348153591156
912 0.21565762162208557
913 0.21534256637096405
914 0.21502815186977386
915 0.21471452713012695
916 0.21440163254737854
917 0.21408945322036743
918 0.21377797424793243
919 0.21346725523471832
920 0.2131572663784027
921 0.2128479778766632
922 0.2125394195318222
923 0.2122316062450409
924 0.2119245082139969
925 0.2116180807352066
926 0.2113124281167984
927 0.21100746095180511
928 0.21070320904254913
929 0.21039965748786926
930 0.2100968360900879
931 0.20979471504688263
932 0.20949330925941467
933 0.20919257402420044
934 0.2088925540447235
935 0.20859326422214508
936 0.20829464495182037
937 0.20799674093723297
938 0.20769952237606049
939 

In [19]:
### テスト
torch.save(model.state_dict(), 'myiris.model')

In [20]:
# 5
torch.no_grad()

### 正解率

In [23]:
with torch.no_grad():
    output1 = model(xtest)
    ans = torch.argmax(output1, 1)
print(((ytest == ans).sum().float() / len(ans)).item())

0.9599999785423279
